---
- hosts: all
  tasks:
    - name: kubeadm reset
      shell: kubeadm reset -f
      register: results
    - debug:
        var: results.stdout

# NEED TO ADDRESS THIS ISSUE ---> rm -rf /var/lib/etcd